# Changes here will be overwritten by Copier.
_commit: 0.7.8
_src_path: https://codeberg.org/margau/copier-python-uv.git
code_dir: promtext_cli
container: false
forgejo_publish: true
forgejo_url: https://codeberg.org/margau/promtext-cli
ignore_pylint: false
ignore_pytest: false
ignore_ruff: false
ignore_ruff_format: false
project_description: Prometheus Textfile Tooling
project_name: promtext-cli
pypi_publish: true
pypi_publish_dev: true
scripts:
    promtext: promtext_cli.main:promtext
