name: lint

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:00ff77f64bbd03497a0f7cd8404690941cc2c989f3909a4071ed10a9982724d0

    steps:
      - uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check src || exit 0 
      - name: format with ruff
        run: uv run ruff format --check src || exit 0 
      - name: check with pylint
        run: uv run pylint src || exit 0 