name: publish

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:57ce61af3ab01c57a177e603af0937faf16d89afa770b16113beed1917ede127
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Build the project
        run: uv build
      - name: Publish release to pypi
        run: uv publish
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: Publish dev version to pypi
        run: uv publish
        if: "${{ github.ref == 'refs/heads/main' }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"