---
name: Lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install hatch
      - run: hatch run ci:check
      - run: hatch run ci:lint
